# Create the gitpod user. UID must be 33333.
RUN useradd -l -u 33333 -G sudo -md /home/gitpod -s /bin/bash -p gitpod gitpod

USER gitpod


tasks:
    - command: sudo apt update && sudo apt install neo-vim
    - command: sudo update-alternatives --install /usr/bin/ollama ollama /workspace/ollama/ollama 1
    - command: sudo update-alternatives --install /usr/bin/ngrok ngrok /workspace/ollama/ngrok 1
    - command: ngrok config add-authtoken 2VNEui4RHe47Hx0qwTzjRT3wmsT_2DPn7CjGhVqcXXbSGjt7n
    - command: ngrok http --domain=secure-hog-magical.ngrok-free.app 11434
